settings:
  camera:
    shadows: true
    permissions: true
    recipe:
      ingredients:
        I: IRON_INGOT
        G: GLASS_PANE
        T: GLOWSTONE_DUST
        R: REDSTONE
      shape:
        - IGI
        - ITI
        - IRI
      enabled: false
    transparentWater: true
    #disabling async may cause minor lag spikes. enabling async will cause slower rendering, but won't affect server performance
    renderAsync: false
  messages:
    notready: '&cCameras is still loading, please wait.'
    invfull: '&cYou can not take a picture with a full inventory.'
    delay: '&cPlease wait before taking another picture.'
    nopaper: '&cYou must have paper in order to take a picture.'
    enabled: true
  delay:
    amount: 1000
    enabled: true
